name: thien_phu_app
description: "Công Ty CP Công Nghệ Chế Tạo Máy Thiên Phú - Ứng dụng giới thiệu sản phẩm"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  carousel_slider: ^5.0.0
  url_launcher: ^6.3.1
  smooth_page_indicator: ^1.2.0+3
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  animated_text_kit: ^4.2.3
  flutter_animate: ^4.5.0
  flutter_widget_from_html: ^0.17.2
  supabase_flutter: ^2.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/data/products.json
